namespace PHPIL.Engine.CodeLexer;

/// <summary>
/// Represents the kind of a lexed token in a PHP source file.
/// Used by the lexer to classify every span of characters in the source,
/// and by the AST stage to drive parsing decisions.
/// </summary>
public enum TokenKind : byte
{
    #region General
    
    /// <summary>
    /// A token that could not be classified. Will cause a diagnostic error at the AST stage.
    /// </summary>
    Unknown,
    
    /// <summary>
    /// One or more space or tab characters collapsed into a single token.
    /// </summary>
    Whitespace,
    
    /// <summary>
    /// A line feed character (\n). Carriage returns (\r) are skipped entirely by the lexer.
    /// </summary>
    NewLine,
    
    /// <summary>
    /// The opening PHP tag: &lt;?php
    /// </summary>
    PhpOpenTag,
    
    /// <summary>
    /// The closing PHP tag: ?&gt;
    /// </summary>
    PhpCloseTag,
    
    /// <summary>
    /// A semicolon (;) terminating a statement or expression.
    /// </summary>
    ExpressionTerminator,
    
    /// <summary>
    /// A namespace separator: \
    /// </summary>
    NamespaceSeparator,
    
    /// <summary>
    /// The error suppression operator: @
    /// Suppresses any errors generated by the following expression.
    /// </summary>
    ErrorSuppress,
    
    /// <summary>
    /// A backtick-delimited shell execute string: `ls -la`
    /// Executes the contents as a shell command and returns the output.
    /// </summary>
    ShellExecute,
    
    #endregion

    #region Identifiers
    
    /// <summary>
    /// A PHP variable, including the leading dollar sign: $myVar
    /// </summary>
    Variable,
    
    /// <summary>
    /// A bare identifier — a function name, class name, label, or any word
    /// that did not match a keyword.
    /// </summary>
    Identifier,
    
    #endregion

    #region Literals
    
    /// <summary>
    /// A single or double quoted string literal: 'hello' or "hello"
    /// The token range includes the surrounding quote characters.
    /// </summary>
    StringLiteral,
    
    /// <summary>
    /// An integer numeric literal: 42, 0xFF, 0b1010, 0777
    /// </summary>
    IntLiteral,
    
    /// <summary>
    /// A floating point numeric literal: 3.14, 1.5e10
    /// </summary>
    FloatLiteral,
    
    /// <summary>
    /// The boolean literal true.
    /// </summary>
    TrueLiteral,
    
    /// <summary>
    /// The boolean literal false.
    /// </summary>
    FalseLiteral,
    
    /// <summary>
    /// The null literal: null
    /// </summary>
    NullLiteral,
    
    #endregion

    #region Assignment
    
    /// <summary>
    /// Plain assignment: =
    /// </summary>
    AssignEquals,
    
    /// <summary>
    /// Add and assign: +=
    /// </summary>
    AddAssign,
    
    /// <summary>
    /// Subtract and assign: -=
    /// </summary>
    SubtractAssign,
    
    /// <summary>
    /// Multiply and assign: *=
    /// </summary>
    MultiplyAssign,
    
    /// <summary>
    /// Divide and assign: /=
    /// </summary>
    DivideAssign,
    
    /// <summary>
    /// Modulo and assign: %=
    /// </summary>
    ModuloAssign,
    
    /// <summary>
    /// Power and assign: **=
    /// </summary>
    PowerAssign,
    
    /// <summary>
    /// Concatenate and assign: .=
    /// </summary>
    ConcatAppend,
    
    /// <summary>
    /// Bitwise AND and assign: &amp;=
    /// </summary>
    BitwiseAndAssign,
    
    /// <summary>
    /// Bitwise OR and assign: |=
    /// </summary>
    BitwiseOrAssign,
    
    /// <summary>
    /// Bitwise XOR and assign: ^=
    /// </summary>
    BitwiseXorAssign,
    
    /// <summary>
    /// Left shift and assign: &lt;&lt;=
    /// </summary>
    LeftShiftAssign,
    
    /// <summary>
    /// Right shift and assign: &gt;&gt;=
    /// </summary>
    RightShiftAssign,
    
    /// <summary>
    /// Null coalesce and assign: ??=
    /// Assigns the right-hand value only if the left-hand side is null.
    /// </summary>
    NullCoalesceAssign,
    
    #endregion

    #region Arithmetic Operators
    
    /// <summary>
    /// Addition: +
    /// </summary>
    Add,
    
    /// <summary>
    /// Subtraction or negation: -
    /// </summary>
    Subtract,
    
    /// <summary>
    /// Multiplication: *
    /// </summary>
    Multiply,
    
    /// <summary>
    /// Division: /
    /// </summary>
    DivideBy,
    
    /// <summary>
    /// Modulo (remainder): %
    /// </summary>
    Modulo,
    
    /// <summary>
    /// Exponentiation: **
    /// </summary>
    Power,
    
    /// <summary>
    /// Pre/post increment: ++
    /// </summary>
    Increment,
    
    /// <summary>
    /// Pre/post decrement: --
    /// </summary>
    Decrement,
    
    #endregion

    #region Bitwise Operators
    
    /// <summary>
    /// Bitwise left shift: &lt;&lt;
    /// </summary>
    LeftShift,
    
    /// <summary>
    /// Bitwise right shift: &gt;&gt;
    /// </summary>
    RightShift,
    
    /// <summary>
    /// Bitwise NOT (unary complement): ~
    /// </summary>
    BitwiseNot,
    
    /// <summary>
    /// Bitwise XOR: ^
    /// </summary>
    BitwiseXor,
    
    /// <summary>
    /// Bitwise AND, or pass-by-reference marker: &amp;
    /// Context determines which role it plays at the AST stage.
    /// </summary>
    Ampersand,
    
    /// <summary>
    /// Bitwise OR: |
    /// </summary>
    BitwiseOr,
    
    #endregion

    #region Logical Operators
    
    /// <summary>
    /// Logical AND operator: &amp;&amp;
    /// </summary>
    LogicalAnd,
    
    /// <summary>
    /// Logical OR operator: ||
    /// </summary>
    LogicalOr,
    
    /// <summary>
    /// Logical NOT operator: !
    /// </summary>
    Not,
    
    /// <summary>
    /// Logical AND keyword: and
    /// Lower precedence than &amp;&amp;.
    /// </summary>
    LogicalAndKeyword,
    
    /// <summary>
    /// Logical OR keyword: or
    /// Lower precedence than ||.
    /// </summary>
    LogicalOrKeyword,
    
    /// <summary>
    /// Logical XOR keyword: xor
    /// </summary>
    LogicalXorKeyword,
    
    #endregion

    #region Comparators
    
    /// <summary>
    /// Less than: &lt;
    /// </summary>
    LessThan,
    
    /// <summary>
    /// Greater than: &gt;
    /// </summary>
    GreaterThan,
    
    /// <summary>
    /// Less than or equal: &lt;=
    /// </summary>
    LessThanOrEqual,
    
    /// <summary>
    /// Greater than or equal: &gt;=
    /// </summary>
    GreaterThanOrEqual,
    
    /// <summary>
    /// Strict equality (type and value): ===
    /// </summary>
    DeepEquality,
    
    /// <summary>
    /// Loose equality (value only, with type coercion): ==
    /// </summary>
    ShallowEquality,
    
    /// <summary>
    /// Strict inequality: !==
    /// </summary>
    DeepInequality,
    
    /// <summary>
    /// Loose inequality: !=
    /// </summary>
    ShallowInequality,
    
    /// <summary>
    /// Spaceship operator: &lt;=&gt;
    /// Returns -1, 0, or 1 based on comparison of left and right operands.
    /// </summary>
    Spaceship,
    
    #endregion

    #region Null Operators
    
    /// <summary>
    /// Null coalescing operator: ??
    /// Returns the left operand if it is not null, otherwise the right.
    /// </summary>
    NullCoalesce,
    
    /// <summary>
    /// Ternary question mark: ?
    /// The colon half of the ternary is tokenised as <see cref="Colon"/>.
    /// </summary>
    QuestionMark,
    
    #endregion

    #region Keywords — Control Flow
    
    /// <summary>if</summary>
    If,
    
    /// <summary>else</summary>
    Else,
    
    /// <summary>elseif</summary>
    ElseIf,
    
    /// <summary>endif</summary>
    EndIf,
    
    /// <summary>while</summary>
    While,
    
    /// <summary>endwhile</summary>
    EndWhile,
    
    /// <summary>do — used in do/while loops.</summary>
    Do,
    
    /// <summary>for</summary>
    For,
    
    /// <summary>endfor</summary>
    EndFor,
    
    /// <summary>foreach</summary>
    Foreach,
    
    /// <summary>endforeach</summary>
    EndForeach,
    
    /// <summary>switch</summary>
    Switch,
    
    /// <summary>endswitch</summary>
    EndSwitch,
    
    /// <summary>match — match expression introduced in PHP 8.</summary>
    Match,
    
    /// <summary>case</summary>
    Case,
    
    /// <summary>default — default case in switch/match.</summary>
    Default,
    
    /// <summary>break</summary>
    Break,
    
    /// <summary>continue</summary>
    Continue,
    
    /// <summary>return</summary>
    Return,
    
    /// <summary>goto</summary>
    Goto,
    
    /// <summary>declare</summary>
    Declare,
    
    /// <summary>enddeclare</summary>
    EndDeclare,
    
    #endregion

    #region Keywords — Exception Handling
    
    /// <summary>try</summary>
    Try,
    
    /// <summary>catch</summary>
    Catch,
    
    /// <summary>finally</summary>
    Finally,
    
    /// <summary>throw</summary>
    Throw,
    
    #endregion

    #region Keywords — OOP
    
    /// <summary>class</summary>
    Class,
    
    /// <summary>const</summary>
    Const, 
    
    /// <summary>interface</summary>
    Interface,
    
    /// <summary>trait</summary>
    Trait,
    
    /// <summary>enum — backed and pure enums introduced in PHP 8.1.</summary>
    Enum,
    
    /// <summary>abstract</summary>
    Abstract,
    
    /// <summary>final</summary>
    Final,
    
    /// <summary>readonly — readonly classes and properties introduced in PHP 8.1.</summary>
    Readonly,
    
    /// <summary>extends</summary>
    Extends,
    
    /// <summary>implements</summary>
    Implements,
    
    /// <summary>instanceof</summary>
    Instanceof,
    
    /// <summary>insteadof — used in trait conflict resolution.</summary>
    Insteadof,
    
    /// <summary>new</summary>
    New,
    
    /// <summary>public</summary>
    Public,
    
    /// <summary>protected</summary>
    Protected,
    
    /// <summary>private</summary>
    Private,
    
    /// <summary>static</summary>
    Static,
    
    /// <summary>use — imports a namespace, trait, or closure binding.</summary>
    Use,
    
    /// <summary>namespace</summary>
    Namespace,
    
    #endregion

    #region Keywords — Functions and Generators
    
    /// <summary>function</summary>
    Function,
    
    /// <summary>fn — short arrow function syntax introduced in PHP 7.4.</summary>
    Fn,
    
    /// <summary>yield — returns a value from a generator function.</summary>
    Yield,
    
    /// <summary>yield from — delegates to another generator or iterable.</summary>
    YieldFrom,
    #endregion

    #region Keywords — Misc
    
    /// <summary>echo — outputs one or more strings.</summary>
    Echo,
    
    /// <summary>print — outputs a string, always returns 1.</summary>
    Print,
    
    /// <summary>die — outputs an optional message and terminates execution. Alias of exit.</summary>
    Die,
    
    /// <summary>unset — destroys a variable.</summary>
    Unset,
    
    /// <summary>list — assigns variables as if they were an array.</summary>
    List,
    
    /// <summary>array — array language construct.</summary>
    Array,
    
    /// <summary>callable — callable type hint.</summary>
    Callable,
    
    /// <summary>include — includes and evaluates a file. Emits a warning on failure.</summary>
    Include,
    
    /// <summary>include_once — includes a file only if it has not already been included.</summary>
    IncludeOnce,
    
    /// <summary>require — includes and evaluates a file. Emits a fatal error on failure.</summary>
    Require,
    
    /// <summary>require_once — requires a file only if it has not already been included.</summary>
    RequireOnce,
    
    #endregion

    #region Structure and Punctuation
    
    /// <summary>
    /// Left parenthesis: (
    /// </summary>
    LeftParen,
    
    /// <summary>
    /// Right parenthesis: )
    /// </summary>
    RightParen,
    
    /// <summary>
    /// Left curly brace: {
    /// </summary>
    LeftBrace,
    
    /// <summary>
    /// Right curly brace: }
    /// </summary>
    RightBrace,
    
    /// <summary>
    /// Left square bracket: [
    /// </summary>
    LeftBracket,
    
    /// <summary>
    /// Right square bracket: ]
    /// </summary>
    RightBracket,
    
    /// <summary>
    /// Fat arrow used in array literals and match arms: =&gt;
    /// </summary>
    Arrow,
    
    /// <summary>
    /// Object access operator: -&gt;
    /// </summary>
    ObjectOperator,
    
    /// <summary>
    /// Nullsafe object access operator: ?-&gt;
    /// Short-circuits to null if the left-hand side is null.
    /// </summary>
    NullsafeOperator,
    
    /// <summary>
    /// Static/scope resolution operator: ::
    /// </summary>
    ScopeResolution,
    
    /// <summary>
    /// Spread or collect operator: ...
    /// Used to unpack iterables into arguments, or collect variadic parameters.
    /// </summary>
    CollectSpread,
    
    /// <summary>
    /// String concatenation operator: .
    /// </summary>
    Concat,
    
    /// <summary>
    /// Comma separator: ,
    /// </summary>
    Comma,
    
    /// <summary>
    /// Colon: used in ternary expressions, named arguments, and alternative control flow syntax.
    /// </summary>
    Colon,
    
    #endregion

    #region Comments
    
    /// <summary>
    /// A single line comment beginning with // or #, up to the end of the line.
    /// </summary>
    SingleLineComment,
    
    /// <summary>
    /// A multi-line comment delimited by /* and */. Also covers PHPDoc blocks (/** ... */).
    /// </summary>
    MultiLineComment,
    
    #endregion

    BitwiseAnd,
    Pipe,
    As,
    Exponent
}